### ISSUE TITLE
Glass (and other blocks?) textures do not connect with Optifine

### ISSUE THREAD

**Issue by Xiaminou** [F32Organization/Faithful32-1.10.2#12]
After updating F32 semi-recently connected textures stopped working.

**Comment by StefanTT** [comment]
For anybody reading this issue: please read the beginning of the thread at the end of issue #12.

Tests with FTB Infinity Lite 110 and some extra mods:

* Tested with OptiFine_1.10.2_HD_U_D4: not connected
* Tested with F32 commit f959159 from nov 9, 2016 and optifine D4: not connected
* Tested with F32 commit 0cc997d from may 23, 2016 and optifine D4: not connected
* Tested with F32 commit 0cc997d from may 23, 2016 and optifine D6 in Direwolf 1.10 version 1.2.0: not connected

Please note that commit 0cc997d from may 23, 2016 is the initial commit of F32 1.10. The vanilla glass panes have not changed since.

I doubt that it's a F32 issue. I think that some change in the mods - or an optifine change - has triggered this.

**Comment by Xiaminou** [comment]
Weird.

**Comment by Virenbar** [comment]
Optifine uses files from **minecraft/mcpatcher/ctm** and there no such folder in the pack, so optifine ctm will never work.
Maybe before you had both normal and modded Faithful packs. And optifine ctm was working.
To fix ctm you need to copy folder **minecraft/mcpatcher/ctm** from this pack: https://minecraft.curseforge.com/projects/faithful-1-11/files/2323077.

**Comment by StefanTT** [comment]
Ah - thank you for clarification, that explains it.
The mcpatcher files are present in F32 1.7.10.
I will fix this tonight.

**Comment by StefanTT** [comment]
I added the mcpatcher files, I hope @xMrVizzy that it is Ok that I took them from your pack as @Artemmr suggested. They seem to be almost identical to the F32 1.7.10 version anyways.

**Comment by kraineff** [comment]
Okay.

**Comment by StefanTT** [comment]
@Xiaminou could you please test if the issue is now fixed for you?

**Comment by Xiaminou** [comment]
it is
